// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-QgSj66gC3YgSkd_Uvouqdl7Lv1518qA',
    appId: '1:126656407781:web:a9be29fe16b64a4bbccc0c',
    messagingSenderId: '126656407781',
    projectId: 'rider-542f0',
    authDomain: 'rider-542f0.firebaseapp.com',
    storageBucket: 'rider-542f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl_Mu1Ifj7cCuOZzMhPulqZ16tF8W92Hc',
    appId: '1:126656407781:android:06ef7f1611be36d3bccc0c',
    messagingSenderId: '126656407781',
    projectId: 'rider-542f0',
    storageBucket: 'rider-542f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDok41O4qP6irx6AiPZGIO_9SLNKh8uF1g',
    appId: '1:126656407781:ios:76a9c6a1913fa08abccc0c',
    messagingSenderId: '126656407781',
    projectId: 'rider-542f0',
    storageBucket: 'rider-542f0.appspot.com',
    iosBundleId: 'com.songchanghao.corider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDok41O4qP6irx6AiPZGIO_9SLNKh8uF1g',
    appId: '1:126656407781:ios:a8a32ad49a7499debccc0c',
    messagingSenderId: '126656407781',
    projectId: 'rider-542f0',
    storageBucket: 'rider-542f0.appspot.com',
    iosBundleId: 'com.example.corider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-QgSj66gC3YgSkd_Uvouqdl7Lv1518qA',
    appId: '1:126656407781:web:3315e6279f725aa0bccc0c',
    messagingSenderId: '126656407781',
    projectId: 'rider-542f0',
    authDomain: 'rider-542f0.firebaseapp.com',
    storageBucket: 'rider-542f0.appspot.com',
  );
}
